<?php include("./includes/header.php"); ?>
<?php include("./includes/nav_inn.php"); ?>
<div class="w-full px-8 space-y-4 montserrat- mt-8">
    <p class="text-3xl font-bold">How to provide a great branding experience when choosing graphics...</p>
    <p>Have you ever heard the saying a picture tells 1000 words? Cliche I know, but it does have truth behind it. Graphics are such a huge component to an exhibition stand. Many design fundamentals need to be considered to ensure that a great branding experience is being achieved. Below are 4 key principles to tick off your list when deciding on graphics for your booth.</p>
    <p class="text-xl">Clear Brand Messaging</p>
    <p>Clear messaging is crucial for your brand communication. The story you tell your potential clients needs to be clear and concise. Communicate to people exactly who you are, the products and services you offer, your key location and what they need to do to get in contact in the future. All these steps set you up for long term client. The graphics that you choose should highlight your brand’s message in a manner that leaves no questions in the mind of visitors on who you are and what you do. To do this, you want clear images, you want the graphics to follow a logical and sequential order, as well as making it clear what actions the visitors need to take to contact you.
</p>
<p class="text-xl">Brand Recognition</p>
<p>Think about all the large brands which are instantly recognisable. Generally, it is through a certain colour, slogan or logo/icon.
In order to achieve this, all these brands do an excellent job at ensuring their most recognisable elements are continuous and consistent through ALL components of advertising and marketing.
Essentially it is like a switch, the moment you see their graphic, logo or slogan you instantaneously know exactly who they are and what they do.
The material you share through various forms of marketing will form the foundation for your brand and recognition, so you want to ensure that clientele can easily recognise who you are. Branded graphic imagery will ensure a brand and message is well remembered.
The goal is to ensure when a person is thinking about purchasing a certain product, your brand initially comes to mind first, as this already dictates their purchase path when choosing your brand over others.</p>
<p class="text-xl">Ensure You Are Attracting Your Ideal Client</p>
<p>When working on your graphics, ensure you can clearly identify what your brand stands for and who your key target market is. Defining this will then essentially dictate what colours, fonts and features you will use. Choosing elements that will appeal most to your target market is important. As this will not only attract them but also trigger certain emotions, feelings and thoughts. For example, if your target market were male, you would choose certain colours that have a more masculine tone or appeal and also products that would resonate with them and their lifestyle.</p>
<p>Essentially you want your key messaging to really engage with your target market and allow them to understand exactly how you can satisfy their needs best.</p>
<p class="text-xl">Remember these Graphics need to work on a LARGE scale</p>
<p>A common misconception we tend to come across when it comes to designing graphics for a stand is that 2D graphics can essentially be used for a 3D layout as well. This isn’t always the case and can sometimes be noticed too late. Magazine ads or a Facebook posts may look fantastic on a small scale, but it isn’t always the correct layout or design for a much larger scale print. Issues that frequently arise are logos being placed in the bottom corners, which in theory works great for a 2D print but obviously for something on a much larger scaler, it will either be hidden or not even noticed. Imagery can often be in incorrect positions which again works great on paper but on a larger scale, it will be hidden by either a product, TV or other stand component. So, ensuring that you have considered how an image or print will appear on a much larger or greater scale is important. This also can come down to the actual size of the image, some images may have been excellent and great quality for an ad but once taken to a much larger scale become blurry or pixelated.</p>
<p>Graphics create such a story and essentially show certain things off in a way that can’t be achieved with only words. They help enhance products and services and catch a passers eye. Your aim is to really stand out from your competitors, make it easy for visitors to recognise you and your brand and in return really listen to what it is you are trying to say.</p>
</div>